version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
